### PR TITLE
fix(step-details): Step's details panel is referencing an old value

### LINKED ISSUE #1561: Sometimes the provided data in config panel field are ignored
### Describe the Bug

Sometimes the provided dat avalues are ignored. i wasn't able to determine steps to reproduce but it happens quite regularly (like very 4 or 5 times I try to modify a different step)

I found only this stack in log:
```
stepsService.ts:539 Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at stepsService.ts:539:44
    at Array.forEach (<anonymous>)
    at StepsService.updateStepParameters (stepsService.ts:537:33)
    at Object.<anonymous> (Visualization.tsx:149:20)
    at invokeFunc (index.js:160:1)
    at trailingEdge (index.js:207:1)
    at timerExpired (index.js:195:1)
 ```

### Steps to Reproduce the Bug or Issue

Not found

### Screenshots or Videos

dataVanished

### Platform

- OS: Fedora
- Browser:  VS Code and Firefox with OperateFirst
- Version: 0.7.5 and main branch on operateFirst

### PR DESCRIPTION
**Pull request by lordrip**
### Description
Currently, when opening the step’s details tab, it’s not referencing the most recent values but keeping the previous values from a previous step.

This generates unintentional changes to a different step than the user is intending to.

This situation was caused because of the addition of a `debounce` function with the intention to only save the [form’s values after the user’s input stopped](https://github.com/KaotoIO/kaoto-ui/pull/1537).

The problem was that the `debounce` function was causing to capture the form’s value from the previous render, hence saving the wrong values to the previous step.

To avoid this situation in the future, the saveConfig function now receives the original step and the new values.

### Changes
* Refactor `saveConfig` callback to receive the original step as a parameter
* Replace lodash' debounce function with `useDebounceCallback()`
* Increase the `debounce` timer from `500ms` to `1s`
* Update `onChangeModel` signature to `(configuration: Record<string, unknown>, isValid: boolean)` to reflect more accurately the intended parameters.
* Remove the `lodash.debounce` dependency since is no longer required

### Before
[Screencast from 2023-03-29 07-46-54.webm](https://user-images.githubusercontent.com/16512618/228438294-6f09f14c-278c-446a-a061-485b009ed068.webm)

### After
[Screencast from 2023-03-29 07-50-39.webm](https://user-images.githubusercontent.com/16512618/228438861-0af6eaf9-199f-43f2-8937-209f82bf620c.webm)

fix: https://github.com/KaotoIO/kaoto-ui/issues/1561

### CODE REVIEW

**Review by unsortedhashsets — DISMISSED** [review]
LGTM, + tested with blocked E2E test

**Review by apupier — DISMISSED** [review]
From functional point of view, I tried with VS Code and it is working better. No more able to reproduce the data loss.

**Review by kahboom — DISMISSED** [review]
LGTM!

**Comment by kahboom** [comment]
@lordrip only thing is that you have some dependency conflicts in `package.json` you'll have to resolve before merging

**Pull request merged**
