### PR TITLE
Upgrade to yarn V3

### LINKED ISSUE #1588: Upgrade to yarn v3
### Please describe the task that needs to be done

currently using yarn v1
migration guide https://yarnpkg.com/getting-started/migration

it will be nice to upgrade other repositories using yarn too.

Advantages:
* Be on active development version. y[arn 1.x is in maintenance mode since January 2020](https://classic.yarnpkg.com/lang/en/docs/install/#debian-stable)

### PR DESCRIPTION
**Pull request by MohammadiIram**
Which issue(s) this PR fixes #1588

### CODE REVIEW

**Comment by lordrip** [comment]
Hi @MohammadiIram :), I think that we're missing the `yarn` binary from this pull request.

It should be the step #6 from [the guide](https://yarnpkg.com/getting-started/migration/#step-by-step)
image

Another thing that we would need to check is publishing the Kaoto package to the npm repository it's working as well, because if I'm not mistaken, there's also a required change from the registry config file, I could be wrong, though.

If you could please upload the missing bits, I think that I can help to check the publishing part :)

**Review by lordrip — CHANGES_REQUESTED** [review]
I think that we're in the right direction, just missing a few little adjusts here and there

**Comment by MohammadiIram** [comment]
> Hi @MohammadiIram :), I think that we're missing the `yarn` binary from this pull request.
> 
> It should be the step #6 from [the guide](https://yarnpkg.com/getting-started/migration/#step-by-step) image
> 
> Another thing that we would need to check is publishing the Kaoto package to the npm repository it's working as well, because if I'm not mistaken, there's also a required change from the registry config file, I could be wrong, though.
> 
> If you could please upload the missing bits, I think that I can help to check the publishing part :)
Hello, @lordrip I've already completed step 6, but i am getting merge conflicts and i am not sure which changes i should keep

**Comment by lordrip** [comment]
If I'm not mistaken, the `yarn.lock` file differs from yarn `v1` to `v3`, so my guess would be that the conflicts come from there. Given that there were a few dependencies updated, probably makes sense to follow the step one more time but start with the latest `main` branch.

If you agree with this, from our side we can pause updating dependencies during the migration as well.

**Comment by MohammadiIram** [comment]
> If I'm not mistaken, the `yarn.lock` file differs from yarn `v1` to `v3`, so my guess would be that the conflicts come from there. Given that there were a few dependencies updated, probably makes sense to follow the step one more time but start with the latest `main` branch.
> 
> If you agree with this, from our side we can pause updating dependencies during the migration as well.

Hello @lordrip
Sorry for the delayed response. Yes, it would be great if you could pause updating dependencies. Since I'm dealing with merge conflicts, should I create a new PR and repeat this process?

**Comment by igarashitm** [comment]
Hi @MohammadiIram 
We can stop merging dependabot ones right when you work on for a few days, so please let us know when. I think you'd be better recreate the PR if you don't see it easy to resolve the conflicts.

**Comment by MohammadiIram** [comment]
> Hi @MohammadiIram We can stop merging dependabot ones right when you work on for a few days, so please let us know when. I think you'd be better recreate the PR if you don't see it easy to resolve the conflicts.

I am ready to work on this issue, and sure, I will recreate this PR.

**Comment by lordrip** [comment]
> I am ready to work on this issue, and sure, I will recreate this PR.

Awesome @MohammadiIram, thanks a lot. I'll pause merging new dependencies in the meantime :+1:

**Comment by lordrip** [comment]
Closing this pull request in favor of https://github.com/KaotoIO/kaoto-ui/pull/1922

**Pull request closed without merging**
