### PR TITLE
feature(test): Adding coverage and codecov reporting

### PR DESCRIPTION
**Pull request by Delawen**
Let's see if it works.

### CODE REVIEW

**Comment by Delawen** [comment]
SonarCloud, are you jealous because I added Codecov? My commit does not have any duplications.

**Comment by kahboom** [comment]
@Delawen why did we add another check when it's failing?

**Comment by Delawen** [comment]
You mean sonarcloud? 

Well, we can tweak the levels at which we want it to fail. But it is better to know it than to have no checks.

**Comment by Delawen** [comment]
Btw: sonarcloud quality gate only considers the code from the last few days. This one is considering all the code because it was the first one. That's why it fails.

**Pull request merged**
