### PR TITLE
Change tittle from 'Step Details' to actual component name

### PR DESCRIPTION
**Pull request by mmelko**
Move Delete button from tabs to details panel

### CODE REVIEW

**Review by kahboom — CHANGES_REQUESTED** [review]
@mmelko I don't see anywhere that you removed the other icon from the Detail panel. Do you have a screenshot to show what it looks like? Just because we don't want to have two icons for that view.

**Comment by mmelko** [comment]
@kahboom yeah I didn't .. going to do that, thanks

**Comment by mmelko** [comment]
@kahboom done, you can check from my branch if the layout works for you.

**Comment by kahboom** [comment]
@mmelko did you push those changes? I still don't see them

**Comment by mmelko** [comment]
ooopps .. look again please it should be there now

**Review by kahboom — APPROVED** [review]

**Pull request merged**
