### PR TITLE
fix(kogito-integration): Set DSL if differs from the settings

### LINKED ISSUE #145: When opening a Camel Route, the type is set to Integration and the catalog is for kamelet binding
TypeSetToIntegration

### PR DESCRIPTION
**Pull request by mmelko**
fixes: https://github.com/KaotoIO/vscode-kaoto/issues/145

### CODE REVIEW

**Comment by apupier** [comment]
I still have the same kind of problem:
image

(opening a kameletbinding file as the default type is now Camel route)

**Comment by mmelko** [comment]
@apupier  it's working for me: bugfix

**Review by apupier — APPROVED** [review]
tried again and it is working fine. I guess I didn't updated correctly the first time. Sorry :-(

Thank you for the fix!

**Comment by mmelko** [comment]
np :) thanks !

**Pull request merged**
