### PR TITLE
fix (GitHub_Actions):Fixing issue related to warning Unexpected input(s) 'username' for Generate Docker image 

### LINKED ISSUE #1539: Fix issue related to warning `Unexpected input(s) 'username'` for `Generate Docker image` GitHub Actions
### Please describe the task that needs to be done

image

### PR DESCRIPTION
**Pull request by MohammadiIram**
Which issue(s) this PR fixes #1539

### CODE REVIEW

**Comment by kahboom** [comment]
thanks for this @MohammadiIram , it would be good to get a quick review from @apupier though he is at the F2F this week

**Comment by lordrip** [comment]
Compared the input list against [the docs](https://github.com/docker/metadata-action#inputs) and there's no `username` property.

**Comment by lordrip** [comment]
Also, the `DeepScan` issue is failing because of an `unused` import which is not related to this pull request.

**Comment by lordrip** [comment]
Almost forgot, thanks @MohammadiIram for taking care of this :smile:

**Pull request merged**
